version: '3.8'

services:
  ###> BDD ###
  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    #command: mysqld --sql_mode=""
    ports:
      - "3308:3306"
    networks:
      - mynetwork
    restart: 'always'
    volumes:
      - type: volume
        source: db-data
        target: /var/lib/mysql:rw

    # Service phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
    ports:
      - "8083:80"
    links:
      - database
    networks:
      - mynetwork

  webserver:
    build:
      context: .
      dockerfile: ./docker/webserver/Dockerfile
    ports:
      - "8082:80"
    restart: 'always'
    links:
      - database
    networks:
      - mynetwork
    volumes:
      - ./:/var/www/
      #links:
      #  - database
      #volumes: 
      # - ./:/var/www/


  mailcatcher:

    image: schickling/mailcatcher
    ports:
      - "1025:1025"
    networks:
      - mynetwork



networks:
  mynetwork:

volumes:
  ###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
